### ISSUE TITLE
Two questions about `GCNConv` 

### ISSUE THREAD

**Issue by spahng** [alexOarga/haiku-geometric#5]
Hi Alex,

Thanks for bringing GNN to Jax! 

I checked the result of haiku-geometric's GCN convolution against a dense version (no weight, just the pre/post-degree weighted graph convolution) and it was off by a bit. I think this is due to adding `ones` to an existing edge in line 121 of `gcn_conv.py`.

`d = edges + jnp.ones_like(conv_senders).reshape(-1, 1)`

Why do you add this `ones`? Can't we directly segment-sum the `edges` instead?

PS: `self.bias` term doesn't seem to get used in the `__call__()` 
PS2: Haiku now recommends using Flax instead. Would you be interested in rewriting NN portion of the code basis in Flax or Equinox?

**Comment by alexOarga** [comment]
Hi spahng,

Sorry for the late reply, I have been quite busy these past few days.
Thanks for trying out Haiku Geometric!

I have reviewed the ones `jnp.ones_like(conv_senders)` and I believe it's safe to remove these.
Will remove them shortly.

Regarding PS1: yes, the term `self.bias` is indeed missing and should be added at the end of the layer :).
Regarding PS2: I think the easiest solution would be to create a new library (e.g. Flax Geometric, and migrate everything there by rewriting the modules. Equinox is also a nice alternative, but at the moment, Flax seems to have broader usage. I will open a new issue to track this process and link the new project.

**Comment by spahng** [comment]
Thank you!
